

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/metrics
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - data-excel-template-app-networks

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: metrics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-excel-template-app-networks
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9095:8080"
    networks:
      - data-excel-template-app-networks
    restart: unless-stopped


volumes:
  postgres_data:
networks:
  data-excel-template-app-networks:
